# Version of docker-compose.
version: "3"

# Containers we're going to run.
services:
  phoenix:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    environment:
      PGHOST: db
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      PORT: 5432
    restart: always
    ports:
      - "4001:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
